### ISSUE TITLE
release operation does not enclose version number with brackets

### ISSUE THREAD

**Issue by fkleedorfer** [superfaceai/release-changelog-action#229]
When updating the changelog, the action renders the version '2.0.0' as 
```
## 2.0.0 - 2022-10-20
```
instead of the expected
```
## [2.0.0] - 2022-10-20
```

**Comment by fkleedorfer** [comment]
On second thought, it must be a subsequent formatting step that does that.

**Comment by janhalama** [comment]
Hi, when releasing the first version of your software the version number is not wrapped in  square brackets. The reason is that we can not create link to changes with previous version (which do not exist).

**Comment by fkleedorfer** [comment]
When I look at your example in the blog post about this, and at https://keepachangelog.com/, the version number is not a link (no round brackets after the square brackets). Is your action handling it differently?

**Comment by fkleedorfer** [comment]
So, here is my changelog before the release:
```
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Changed

- Improve Changelog handling during release

## [2.0.0] - 2022-10-20

### Added

- Add module `qudtlib-js-gen`, which generates Typescript code to instantiate units, quantitykinds and prefixes for `qudtlib/qudtlib-js`
- Add project `qudtlib-js` as a git submodule to allow the build process to generate javascript into that project
- Add `Qudt.*required` static methods that return e.g. `Unit`, not `Optional<Unit>` and throw an Exception if there is nothing to return.

### Changed

- A number of breaking changes without prior deprecations, sorry about that.
- Upgrade to QUDT v2.1.19
- Move any code from `Qudt` to model classes (`Unit`, `QuantityValue`, etc.) if the code does not directly depend on pre-instantiated units.
- Refactor `Qudt.*` static methods to return `Optional`s where appropriate
- Made `Qudt.convert(BigDecimal, Unit, Unit)` return `BigDecimal` (was:`QuantityValue`) while `Qudt.convert(QuantityValue, Unit)` still returns a `QuantityValue`. It's cleaner: you get what you provide.
- Refactor factor unit matching (fixing some bugs in the process)
- Fix errors in RDF generation
- Fix errors in generation of constants (such as `Qudt.Units.M`)
- Improve unit tests
- Change `toString()` methods in a number of model classes for better readability
- Upgrade dependencies to latest versions

### Removed

- Remove unused code

## [1.0.0] - 2022-07-21

Initial release.
```
And this is the changelog for Release 2.0.1. 
```
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## Unreleased

## 2.0.1 - 2022-10-20

### Changed

- Improve Changelog handling during release

## 2.0.0 - 2022-10-20

### Added

- Add module `qudtlib-js-gen`, which generates Typescript code to instantiate units, quantitykinds and prefixes for `qudtlib/qudtlib-js`
- Add project `qudtlib-js` as a git submodule to allow the build process to generate javascript into that project
- Add `Qudt.*required` static methods that return e.g. `Unit`, not `Optional<Unit>` and throw an Exception if there is nothing to return.

### Changed

- A number of breaking changes without prior deprecations, sorry about that.
- Upgrade to QUDT v2.1.19
- Move any code from `Qudt` to model classes (`Unit`, `QuantityValue`, etc.) if the code does not directly depend on pre-instantiated units.
- Refactor `Qudt.*` static methods to return `Optional`s where appropriate
- Made `Qudt.convert(BigDecimal, Unit, Unit)` return `BigDecimal` (was:`QuantityValue`) while `Qudt.convert(QuantityValue, Unit)` still returns a `QuantityValue`. It's cleaner: you get what you provide.
- Refactor factor unit matching (fixing some bugs in the process)
- Fix errors in RDF generation
- Fix errors in generation of constants (such as `Qudt.Units.M`)
- Improve unit tests
- Change `toString()` methods in a number of model classes for better readability
- Upgrade dependencies to latest versions

### Removed

- Remove unused code

## 1.0.0 - 2022-07-21

Initial release.

```

I checked: our formatter (maven spotless plugin with markdown formatting through flexmark with default settings) does not touch the file prior to the release, so I think the changes to the version numbers are made by this action. Is that the intended behaviour?

**Comment by janhalama** [comment]
Hi, your Changelog contains "broken" markdown [Reference-style Links](https://www.markdownguide.org/basic-syntax/#reference-style-links) without actual link in the footer part of your markdown file. You need to provide at least one link to changes in your CHANGELOG.nd file, to get it working (to provide your git repository base url). To fix this add to the end of your changelog file following line:

```
[Unreleased]: <url to your github repository>/compare/v2.0.0...HEAD
```

I agree that this behaviour is confusing and should be documented. Also passing your git repository base url through action parameters should be supported.

**Comment by fkleedorfer** [comment]
Thanks for that hint! I was not aware of this markdown feature and I had not understood the Changelog file footer util now. Will experiment and report!

**Comment by fkleedorfer** [comment]
> I agree that this behaviour is confusing and should be documented.

I would have been really ok with the action just failing in this case - ideally with an error message that helps me to fix the problem

**Comment by fkleedorfer** [comment]
I've fixed my `Changelog.md` and ran the release again. It reveals a related problem: the action assumes that the version tags use the format `v${version}`, which I haven't been using. My footer was:
```
[Unreleased]: https://github.com/qudtlib/qudtlib-java/compare/2.0.0...HEAD
[2.0.0]: https://github.com/qudtlib/qudtlib-java/compare/qudtlib-java-1.0...2.0.0
[1.0.0]: https://github.com/qudtlib/qudtlib-java/releases/tag/qudtlib-java-1.0
```
and now is:
```
[Unreleased]: https://github.com/qudtlib/qudtlib-java/compare/v2.0.1...HEAD
[2.0.1]: https://github.com/qudtlib/qudtlib-java/compare/v2.0.0...v2.0.1
[2.0.0]: https://github.com/qudtlib/qudtlib-java/compare/v1.0.0...v2.0.0
```

Problems:
- the 1.0.0 entry is gone completely
- all other entries use tags that the project just does not have

I had an inconsistency there already, as the tag for version 1.0.0 is the default tag generated by the maven release plugin, but that turned out to be impractical for other steps in my release process, so I changed the format. I did not want to go and change the old tag, though, because I was unsure if it wasn't referenced somewhere. I'll go and add tags adhering to the `v${version}` pattern, adapt the build and release again, and report back.

Again, if the action just failed, it would be easier to get to a correct changelog.

**Comment by fkleedorfer** [comment]
Almost.
Before release:
```
[Unreleased]: https://github.com/qudtlib/qudtlib-java/compare/v2.0.0...HEAD
[2.0.0]: https://github.com/qudtlib/qudtlib-java/compare/v1.0.0...v2.0.0
[1.0.0]: https://github.com/qudtlib/qudtlib-java/releases/tag/v1.0.0
```
After release:
```
[Unreleased]: https://github.com/qudtlib/qudtlib-java/compare/v2.0.1...HEAD
[2.0.1]: https://github.com/qudtlib/qudtlib-java/compare/v2.0.0...v2.0.1
[2.0.0]: https://github.com/qudtlib/qudtlib-java/compare/v1.0.0...v2.0.0
```

Problems: 
- the 1.0.0 entry is still gone. 

That is what you meant when you said:

> when releasing the first version of your software the version number is not wrapped in square brackets. The reason is that we can not create link to changes with previous version (which do not exist).

However, in https://keepachangelog.com/en/1.0.0/ the very first version in the changelog is linked to the tag for that reason:

```
[...]
[0.0.3]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.0.2...v0.0.3
[0.0.2]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.0.1...v0.0.2
[0.0.1]: https://github.com/olivierlacan/keep-a-changelog/releases/tag/v0.0.1        <-- no comparison, just the tag
```

I would welcome if the action did that, too, but I am happy with the results I am getting now.

**Comment by janhalama** [comment]
Thanks for your report.

> the 1.0.0 entry is gone completely
This is [fixed in package](https://github.com/oscarotero/keep-a-changelog/issues/21) this action depends on, I will release new version with updated dependency.

> all other entries use tags that the project just does not have
The solution I propose is to add `tag-format` parameter to the action.

**Comment by fkleedorfer** [comment]
Great to hear!

> The solution I propose is to add tag-format parameter to the action.

That should work.
