### ISSUE TITLE
Upgrade to using Environment Files

### ISSUE THREAD

**Issue by janhalama** [superfaceai/release-changelog-action#273]
`set-output` command is deprecated 

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by syJSdev** [comment]
@janhalama I created a PR for fix.

**Comment by janhalama** [comment]
@syJSdev Thank you for your help. I released the fix in [v2.1.3](https://github.com/superfaceai/release-changelog-action/releases/tag/v2.1.3) and  updated [v2](https://github.com/superfaceai/release-changelog-action/tree/v2) tag.
